### ISSUE TITLE
Alias `get_tile_iterator` to `eachtile`

### ISSUE THREAD

**Issue by mkitti** [bionanoimaging/TiledViews.jl#1]
I was thinking of a function named `eachtile` in analogy to `eachslice` or `eachrow` until I found `get_tile_iterator` which does what I want. Would it make sense to create an alias for `get_tile_iterator` named `eachtile`?

**Comment by RainerHeintzmann** [comment]
Thanks! This is a good idea. I will just change the names into eachtile and eachtilenumber. Depending on your application you may also want to look at tiled_processing.

**Comment by RainerHeintzmann** [comment]
did the update. There is now `eachtile`, `eachtilerelpos`, and `eachtilenumber`. Thanks for the suggestion!
