### ISSUE TITLE
Docstring for `TiledView` indicates a optional data type

### ISSUE THREAD

**Issue by roflmaostc** [bionanoimaging/TiledViews.jl#3]
Thanks for the package.

However, I saw in the docstrings
```julia
TiledView([T], data::F, tile_size::NTuple{N,Int}, tile_overlap::NTuple{N,Int}; pad_value::T)
```
which apperently doesn't work.
You might also change `rel_overlap` in the docstring.

Cheers,
Felix

**Comment by RainerHeintzmann** [comment]
Thanks for the hint. Indeed the `[T]` was wrong and several smaller things were not documented correctly. Should be OK now.
